/* Standalone UI and browser-import parity helpers; no network or storage. */
const SeasonLensMarketMath = (()=>{
 const finite=v=>Number.isFinite(v), mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
 const quantile=(a,p)=>{if(!a.length)return null;const v=[...a].sort((x,y)=>x-y),i=(v.length-1)*p,l=Math.floor(i);return v[l]+(v[Math.ceil(i)]-v[l])*(i-l)};
 const shift=(d,n,unit='month')=>{const [y,m,day]=d.split('-').map(Number),x=new Date(0);x.setUTCFullYear(y,unit==='year'?m-1:m-1+n,1);if(unit==='year')x.setUTCFullYear(y+n);const end=new Date(0);end.setUTCFullYear(x.getUTCFullYear(),x.getUTCMonth()+1,0);x.setUTCDate(Math.min(day,end.getUTCDate()));return x.toISOString().slice(0,10)};
 const pct=(a,b)=>a>0&&b>0&&finite(a/b)?(a/b-1)*100:null;
 function returns(rows){return rows.slice(1).map((r,i)=>({date:r.date,start:rows[i].date,value:pct(r.value,rows[i].value)}))}
 function indicators(rows){const rsi14=rows.map(()=>null),volatility20=rows.map(()=>null),volatility60=rows.map(()=>null);let g=0,l=0;const logs=[];for(let i=1;i<rows.length;i++){let delta=rows[i].value-rows[i-1].value;if(i<=14){g+=Math.max(delta,0)/14;l+=Math.max(-delta,0)/14}else{g=g*(13/14)+Math.max(delta,0)/14;l=l*(13/14)+Math.max(-delta,0)/14}if(i>=14)rsi14[i]=g===0&&l===0?50:100*(g/Math.max(g,l))/(g/Math.max(g,l)+l/Math.max(g,l));logs.push(rows[i].value>0&&rows[i-1].value>0?Math.log(rows[i].value)-Math.log(rows[i-1].value):null);for(const w of [20,60])if(logs.length>=w){const a=logs.slice(-w);if(a.every(v=>v!==null&&finite(v))){const m=mean(a),sd=Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(w-1))*100;(w===20?volatility20:volatility60)[i]=finite(sd)?sd:null}}}return {dates:rows.map(r=>r.date),rsi14,volatility20,volatility60}}
 function snapshot(rows,asOf){const last=rows.at(-1),lastDate=last?.date??null,lastValue=last?.value??null,changes={};for(const [key,target] of Object.entries({previous:null,month:shift(asOf,-1),quarter:shift(asOf,-3),ytd:String(Number(asOf.slice(0,4))-1).padStart(4,'0')+'-12-31'})){const ref=key==='previous'?rows.at(-2):rows.filter(r=>r.date<=target).at(-1);changes[key]={target_date:target,reference_date:ref?.date??null,reference_value:ref?.value??null,change:ref&&last?last.value-ref.value:null,change_pct:ref&&last?pct(last.value,ref.value):null}}
 const sma200=rows.length>=200?mean(rows.slice(-200).map(r=>r.value)):null,position={};for(const [key,n] of [['one_year',1],['five_year',5]]){const start=shift(asOf,-n,'year'),a=rows.filter(r=>r.date>=start).map(r=>r.value);position[key]={start_date:start,end_date:asOf,minimum:a.length?Math.min(...a):null,maximum:a.length?Math.max(...a):null,percentile:a.length?100*(a.filter(v=>v<lastValue).length+.5*a.filter(v=>v===lastValue).length)/a.length:null,observation_count:a.length}}
 return {as_of:asOf,last_date:lastDate,last_value:lastValue,observation_count:rows.length,excluded_future_observations:0,changes,sma200,distance_sma200_pct:sma200===null?null:pct(lastValue,sma200),position}}
 function distribution(rows,asOf,n){const end=Number(asOf.slice(0,4))-1,start=end-n+1,groups=new Map();for(const r of rows){const year=Number(r.date.slice(0,4));if(year>=start&&year<=end){const k=r.date.slice(0,7);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r.value)}}const months=[];for(let m=1;m<=12;m++){const selected=[...groups.entries()].filter(([k])=>Number(k.slice(5))===m),values=selected.map(([,a])=>mean(a));months.push({month:m,mean:mean(values),median:quantile(values,.5),q25:quantile(values,.25),q75:quantile(values,.75),year_count:values.length,observation_count:selected.reduce((s,[,a])=>s+a.length,0)})}return {start_year:start,end_year:end,months}}
 function buildMarket(rows,asOf){rows=rows.filter(r=>r.date<=asOf);return {snapshot:snapshot(rows,asOf),indicators:indicators(rows),distribution:{'5':distribution(rows,asOf,5),'10':distribution(rows,asOf,10)}}}
 function correlation(a,b){if(a.length<2)return null;const scaleA=Math.max(1,...a.map(Math.abs)),scaleB=Math.max(1,...b.map(Math.abs));a=a.map(v=>v/scaleA);b=b.map(v=>v/scaleB);const ma=mean(a),mb=mean(b),sa=a.reduce((s,v)=>s+(v-ma)**2,0),sb=b.reduce((s,v)=>s+(v-mb)**2,0);if(!sa||!sb)return null;const result=a.reduce((s,v,i)=>s+(v-ma)*(b[i]-mb),0)/Math.sqrt(sa*sb);return finite(result)?Math.max(-1,Math.min(1,result)):null}
 function pairedReturns(a,b){const lookup=new Map(returns(b).filter(r=>r.value!==null).map(r=>[r.start+'|'+r.date,r]));return returns(a).filter(r=>r.value!==null&&lookup.has(r.start+'|'+r.date)).map(r=>({date:r.date,start:r.start,a:r.value,b:lookup.get(r.start+'|'+r.date).value}))}
 return {mean,quantile,shift,pct,returns,buildMarket,correlation,pairedReturns};
})();
if(typeof globalThis!=='undefined')globalThis.SeasonLensMarketMath=SeasonLensMarketMath;
const marketColors=['#2563eb','#c45d11','#7c3aed','#0f766e','#dc2626','#334155','#be185d','#65a30d'];
const marketFmt=(v,d=3)=>v===null||v===undefined||!Number.isFinite(v)?'—':v.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const marketPct=v=>v===null||v===undefined?'—':marketFmt(v,2)+'%';
function marketCard(label,value,note=''){return `<div class="card"><span class="muted">${esc(label)}</span><strong class="market-value">${esc(value)}</strong><span class="muted">${esc(note)}</span></div>`}
function marketRows(id,units='Original'){const s=data[id];return (s?.views[units]?.daily??s?.views.Original?.daily??[]).filter(r=>r.date<=cutoff)}
function marketRange(rows,key){rows=rows.filter(r=>r.date<=cutoff);const start=key==='all'?null:SeasonLensMarketMath.shift(cutoff,key==='12m'?-12:-3);if(key==='90'){const d=new Date(cutoff+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-90);return rows.filter(r=>r.date>=d.toISOString().slice(0,10))}return start?rows.filter(r=>r.date>=start):rows}
function marketChart(id,rows,lines,{unit='',bounds=null,band=null,references=[]}={}){
 const host=el(id),values=rows.flatMap(r=>lines.map(l=>r[l.key])).filter(v=>v!==null&&Number.isFinite(v));if(!values.length){host.innerHTML='<p>No available observations for this selection.</p>';return}
 if(band)for(const r of rows)for(const k of band)if(Number.isFinite(r[k]))values.push(r[k]);let low=bounds?bounds[0]:values.reduce((m,v)=>Math.min(m,v),Infinity),high=bounds?bounds[1]:values.reduce((m,v)=>Math.max(m,v),-Infinity);if(!bounds){const pad=high>low?(high-low)*.08:Math.abs(low)*.01||1;low-=pad;high+=pad}if(!Number.isFinite(high-low)||high<=low){host.innerHTML='<p>Chart scale unavailable for this numerical range.</p>';return}
 const left=90,right=1050,bottom=255,top=30,t0=Date.parse(rows[0].date+'T00:00:00Z'),t1=Date.parse(rows.at(-1).date+'T00:00:00Z'),x=r=>left+(Date.parse(r.date+'T00:00:00Z')-t0)/Math.max(1,t1-t0)*(right-left),y=v=>bottom-(v-low)/(high-low)*(bottom-top);
 const ticks=Array.from({length:5},(_,i)=>low+(high-low)*i/4);let precision=5,labels;for(;precision<=17;precision++){labels=ticks.map(v=>v.toLocaleString('en-US',{maximumSignificantDigits:precision}));if(new Set(labels).size===5)break}if(precision>17){host.innerHTML='<p>Chart tick precision unavailable for this numerical range.</p>';return}const tick=v=>v.toLocaleString('en-US',{maximumSignificantDigits:precision});
 let out=`<svg viewBox="0 0 1120 310" role="img" aria-label="${esc(lines.map(l=>l.name).join(', '))}"><title>${esc(lines.map(l=>l.name).join(', '))}</title><text x="${left}" y="17">${esc(unit)}</text>`;
 for(let i=0;i<5;i++){const v=low+(high-low)*i/4,yy=y(v);out+=`<line x1="${left}" x2="${right}" y1="${yy}" y2="${yy}" stroke="#e2e8f0"/><text x="${left-8}" y="${yy+4}" text-anchor="end">${esc(tick(v))}</text>`}
 for(const ref of references)out+=`<line x1="${left}" x2="${right}" y1="${y(ref)}" y2="${y(ref)}" stroke="#94a3b8" stroke-dasharray="5 4"/><text x="${right+5}" y="${y(ref)+4}">${ref}</text>`;
 if(band){let segment=[];function flush(){if(segment.length){const points=segment.map(r=>`${x(r)},${y(r[band[1]])}`).concat([...segment].reverse().map(r=>`${x(r)},${y(r[band[0]])}`));out+=`<polygon points="${points.join(' ')}" fill="#ede9fe"/>`;segment=[]}}for(const r of rows){if(Number.isFinite(r[band[0]])&&Number.isFinite(r[band[1]]))segment.push(r);else flush()}flush()}
 for(const l of lines){let path='',open=false;for(const r of rows){const v=r[l.key];if(v===null||!Number.isFinite(v)){open=false;continue}path+=(open?' L ':' M ')+`${x(r)},${y(v)}`;open=true}out+=`<path d="${path}" fill="none" stroke="${l.color}" stroke-width="2.2"${l.dash?' stroke-dasharray="7 4"':''}/>`;if(rows.length===1&&Number.isFinite(rows[0][l.key]))out+=`<circle cx="${x(rows[0])}" cy="${y(rows[0][l.key])}" r="4" fill="${l.color}"/>`}
 out+=`<text x="${left}" y="283">${esc(rows[0].label??rows[0].date)}</text><text x="${right}" y="283" text-anchor="end">${esc(rows.at(-1).label??rows.at(-1).date)}</text></svg><div class="market-legend">`+lines.map(l=>`<span style="--line:${l.color}">${esc(l.name)}</span>`).join('')+(band?'<span style="--line:#c4b5fd">Middle 50% of yearly monthly averages</span>':'')+'</div>';host.innerHTML=out;
}
function marketInitialize(){
 const ids=Object.keys(data),checked=new Set([...el('comparison-instruments').querySelectorAll('input:checked')].map(n=>n.value));el('comparison-instruments').innerHTML=ids.map((id,i)=>`<label><input type="checkbox" value="${esc(id)}" ${checked.size?checked.has(id)?'checked':'':i<3?'checked':''}><span>${esc(data[id].title+(data[id].source==='USER_FILE'?' · private '+(data[id].source_format==='XLSX'?'Excel':'CSV'):data[id].source==='SYNTHETIC'?' · invented sample':' · '+data[id].source))}</span></label>`).join('');
 for(const name of ['correlation-a','correlation-b']){const previous=el(name).value;el(name).replaceChildren();ids.forEach(id=>{const o=document.createElement('option');o.value=id;o.textContent=data[id].title;el(name).append(o)});if(ids.includes(previous))el(name).value=previous;else if(name==='correlation-b'&&ids.length>1)el(name).value=ids[1]}
}
function marketSnapshot(){const v=view(),m=v.market??(v.market=SeasonLensMarketMath.buildMarket(v.daily,cutoff)),s=m.snapshot,d=/^[A-Z]{3} per [A-Z]{3}$/.test(v.unit)?3:0;el('market-cards').innerHTML=marketCard('Last observed price',marketFmt(s.last_value,d)+' '+v.unit,'Observation: '+(s.last_date??'—'))+[['previous','Previous observation'],['month','Trailing 1 month'],['ytd','Year to date']].map(([k,label])=>{const c=s.changes[k];return marketCard(label,marketPct(c.change_pct),'Reference: '+(c.reference_date??'unavailable'))}).join('')+marketCard('Distance from SMA200',marketPct(s.distance_sma200_pct),'SMA200: '+marketFmt(s.sma200,d)) +['one_year','five_year'].map((k,i)=>{const p=s.position[k];return marketCard((i?'5-year':'1-year')+' level percentile',marketPct(p.percentile),`${p.observation_count} observations · ${p.start_date}–${p.end_date} · min ${marketFmt(p.minimum,d)} / max ${marketFmt(p.maximum,d)}`)}).join('');
 const ind=m.indicators,rows=ind.dates.map((date,i)=>({date,rsi14:ind.rsi14[i],volatility20:ind.volatility20[i],volatility60:ind.volatility60[i]})),visible=marketRange(rows,el('range').value);marketChart('volatility-chart',visible,[{key:'volatility20',name:'20-return daily volatility',color:'#2563eb'},{key:'volatility60',name:'60-return daily volatility',color:'#c45d11'}],{unit:'Daily log-return standard deviation (%)'});marketChart('rsi-chart',visible,[{key:'rsi14',name:'RSI 14 (Wilder)',color:'#7c3aed'}],{unit:'RSI',bounds:[0,100],references:[30,70]});marketDistribution();
}
function marketCompatibleFX(s){return marketFXId(s)!==null}
function marketAttribution(){const s=data[el('instrument').value],commodity=marketCompatibleFX(s),fx=commodity?marketRows(marketFXId(s)):[];el('market-attribution').hidden=false;if(!commodity){el('attribution-output').innerHTML='<p>Choose a compatible EUR/t benchmark with explicitly identified EUR/PLN rates. Import a declared EUR/PLN column together with your commodity to use private exact-date conversions. Invented sample FX is never substituted.</p>';return};const f=new Map(fx.map(r=>[r.date,r.value])),rows=s.views.Original.daily.filter(r=>f.has(r.date)&&r.value>0&&f.get(r.date)>0).map(r=>({date:r.date,price:r.value,fx:f.get(r.date),pln:r.value*f.get(r.date)})),end=rows.at(-1),key=el('attribution-period').value,target=key==='month'?SeasonLensMarketMath.shift(cutoff,-1):key==='year'?String(Number(cutoff.slice(0,4))-1).padStart(4,'0')+'-12-31':SeasonLensMarketMath.shift(cutoff,-12),start=key==='day'?rows.at(-2):rows.filter(r=>r.date<=target).at(-1);
 if(!start||!end||start===end){el('attribution-output').innerHTML='<p>Attribution needs two positive, same-date commodity/FX observations and an available period reference.</p>';return}const p=(end.price/start.price-1),fchange=(end.fx/start.fx-1),interaction=p*fchange,total=end.pln/start.pln-1;el('attribution-output').innerHTML='<div class="market-grid">'+marketCard('Commodity contribution',marketFmt(p*100,2)+' pp')+marketCard('FX contribution',marketFmt(fchange*100,2)+' pp')+marketCard('Interaction',marketFmt(interaction*100,2)+' pp')+marketCard('Total PLN price change',marketPct(total*100))+marketCard('Reference PLN/t',marketFmt(start.pln,0),start.date)+marketCard('Latest matched PLN/t',marketFmt(end.pln,0),end.date)+'</div>';
}
function marketComparison(){const ids=[...el('comparison-instruments').querySelectorAll('input:checked')].map(n=>n.value),key=el('comparison-range').value,units=el('comparison-units').value;if(!ids.length){el('comparison-chart').innerHTML='<p>Select at least one instrument.</p>';el('comparison-coverage').textContent='';return}const series=ids.map(id=>marketRange(marketRows(id,units),key)),maps=series.map(rows=>new Map(rows.map(r=>[r.date,r.value]))),dates=series[0].map(r=>r.date).filter(date=>maps.every(m=>m.has(date)));if(!dates.length||maps.some(m=>dates.some(d=>!(m.get(d)>0)))){el('comparison-chart').innerHTML='<p>Comparison requires shared dates and strictly positive prices throughout the selected range.</p>';el('comparison-coverage').textContent='';return}const rows=dates.map(date=>Object.fromEntries([['date',date],...maps.map((m,i)=>['s'+i,m.get(date)/m.get(dates[0])*100])])),lines=ids.map((id,i)=>({key:'s'+i,name:data[id].title+(data[id].source==='USER_FILE'?' · private '+(data[id].source_format==='XLSX'?'Excel':'CSV'):data[id].source==='SYNTHETIC'?' · invented sample':' · '+data[id].source)+' · '+(data[id].views[units]?.unit??data[id].views.Original.unit),color:marketColors[i%marketColors.length]}));marketChart('comparison-chart',rows,lines,{unit:'Common-date price index: start = 100'});el('comparison-coverage').textContent=`${dates.length} shared observations · start ${dates[0]} · end ${dates.at(-1)}. Selected series counts in range: `+series.map((r,i)=>`${data[ids[i]].title}: ${r.length}`).join('; ')+(ids.some(id=>data[id].source==='USER_FILE')&&ids.some(id=>data[id].source==='SYNTHETIC')?' Private CSV and invented sample histories can be displayed together; their sources and quote times may differ.':'')}
function marketCorrelation(){const a=el('correlation-a').value,b=el('correlation-b').value,w=Number(el('correlation-window').value);if(!a||!b)return;const pairs=SeasonLensMarketMath.pairedReturns(marketRows(a),marketRows(b)),rolling=pairs.map((r,i)=>({date:r.date,correlation:i+1>=w?SeasonLensMarketMath.correlation(pairs.slice(i-w+1,i+1).map(x=>x.a),pairs.slice(i-w+1,i+1).map(x=>x.b)):null}));marketChart('correlation-chart',marketRange(rolling,el('range').value),[{key:'correlation',name:`${data[a].title} / ${data[b].title} · ${w} paired returns`,color:'#0f766e'}],{unit:'Pearson correlation',bounds:[-1,1]});const ids=Object.keys(data).slice(0,12);let table='<table><thead><tr><th>Last matched returns</th>'+ids.map(id=>'<th>'+esc(data[id].title)+'</th>').join('')+'</tr></thead><tbody>';for(const id of ids){table+='<tr><th>'+esc(data[id].title)+'</th>';for(const other of ids){const p=SeasonLensMarketMath.pairedReturns(marketRows(id),marketRows(other)).slice(-w),c=p.length===w?SeasonLensMarketMath.correlation(p.map(x=>x.a),p.map(x=>x.b)):null;table+=`<td title="${esc(p.length+' matched intervals'+(p.length?' · '+p[0].start+'–'+p.at(-1).date:''))}">${marketFmt(c,3)}<br><small>n=${p.length}</small></td>`}table+='</tr>'}el('correlation-matrix').innerHTML=table+'</tbody></table>'}
function marketSpread(){const selected=data[el('instrument').value],privateGroup=selected?.source==='USER_FILE'?selected.import_group:null,ids=Object.keys(data),wheat=privateGroup?ids.find(id=>data[id].source==='USER_FILE'&&data[id].import_group===privateGroup&&data[id].role==='wheat'):ids.find(id=>id==='SYNTHETIC_GRAIN'||id==='BL2c1'),corn=privateGroup?ids.find(id=>data[id].source==='USER_FILE'&&data[id].import_group===privateGroup&&data[id].role==='corn'):ids.find(id=>id==='SYNTHETIC_CORN'||id==='EMAc1'),units=el('spread-units').value;if(!wheat||!corn||!data[wheat].views[units]||!data[corn].views[units]||data[wheat].views[units].unit!==data[corn].views[units].unit){el('spread-chart').innerHTML='<p>Wheat and corn need matching EUR/t or PLN/t views. For a private workbook, explicitly assign wheat and corn roles with identical units.</p>';el('spread-context').textContent='';return}const lookup=new Map(marketRows(corn,units).map(r=>[r.date,r.value])),rows=marketRange(marketRows(wheat,units).filter(r=>lookup.has(r.date)).map(r=>({date:r.date,spread:r.value-lookup.get(r.date)})),el('range').value),m=SeasonLensMarketMath.mean(rows.map(r=>r.spread));rows.forEach(r=>r.mean=m);marketChart('spread-chart',rows,[{key:'spread',name:'Wheat minus corn',color:'#2563eb'},{key:'mean',name:'Displayed-period mean',color:'#111827',dash:true}],{unit:data[wheat].views[units].unit});if(rows.length){const last=rows.at(-1).spread,rank=100*(rows.filter(r=>r.spread<last).length+.5*rows.filter(r=>r.spread===last).length)/rows.length;el('spread-context').textContent=`${rows.length} exact-date pairs · last difference ${marketFmt(last,0)} · historical percentile ${marketPct(rank)} (current included; ties receive half weight).`}}
function marketDistribution(){const v=view(),n=el('distribution-years').value,d=v.market.distribution[n],names=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],rows=d.months.map(r=>({...r,date:`2000-${String(r.month).padStart(2,'0')}-01`,label:names[r.month-1]}));marketChart('distribution-chart',rows,[{key:'median',name:'Median yearly monthly average',color:'#7c3aed'},{key:'mean',name:'Mean yearly monthly average',color:'#2563eb'}],{unit:v.unit,band:['q25','q75']});const digits=/^[A-Z]{3} per [A-Z]{3}$/.test(v.unit)?3:0;el('distribution-table').innerHTML=`<table><caption>${d.start_year}–${d.end_year} · ${esc(v.unit)}</caption><thead><tr><th>Month</th><th>Mean</th><th>Median</th><th>25th percentile</th><th>75th percentile</th><th>Years</th><th>Observations</th></tr></thead><tbody>`+d.months.map(r=>'<tr><th>'+names[r.month-1]+'</th>'+['mean','median','q25','q75'].map(k=>'<td>'+marketFmt(r[k],digits)+'</td>').join('')+`<td>${r.year_count}/${n}</td><td>${r.observation_count}</td></tr>`).join('')+'</tbody></table>'}
let scenarioReference=null,scenarioInstrument=null;
function marketScenario(reset=false){const s=data[el('instrument').value];if(!marketCompatibleFX(s)){el('scenario-output').innerHTML='<p>Select an EUR/t benchmark with compatible identified FX to create a commodity/FX scenario.</p>';el('scenario-reference').textContent='';for(const id of ['scenario-price','scenario-fx','scenario-tonnes','scenario-reset'])el(id).disabled=true;scenarioReference=null;return}for(const id of ['scenario-price','scenario-fx','scenario-tonnes','scenario-reset'])el(id).disabled=false;const fx=new Map(marketRows(marketFXId(s)).map(r=>[r.date,r.value])),last=s.views.Original.daily.filter(r=>fx.has(r.date)&&r.value>0&&fx.get(r.date)>0).at(-1);if(!last){el('scenario-output').innerHTML='<p>No positive same-date EUR commodity and EUR/PLN reference is available.</p>';el('scenario-reference').textContent='';scenarioReference=null;return}scenarioReference={price:last.value,fx:fx.get(last.date),date:last.date};if(reset||scenarioInstrument!==el('instrument').value){el('scenario-price').value=last.value;el('scenario-fx').value=scenarioReference.fx;scenarioInstrument=el('instrument').value}const price=Number(el('scenario-price').value),f=Number(el('scenario-fx').value),tonnes=Number(el('scenario-tonnes').value),reference=scenarioReference.price*scenarioReference.fx,pln=price*f,total=pln*tonnes;if(![price,f,tonnes,pln,total,reference].every(Number.isFinite)||!(price>0&&f>0&&tonnes>0)||['scenario-price','scenario-fx','scenario-tonnes'].some(id=>el(id).value.trim()==='')){el('scenario-output').innerHTML='<p>Enter finite positive price and FX values, and a finite positive quantity.</p>';return}el('scenario-output').innerHTML=marketCard('Scenario PLN/t',marketFmt(pln,2))+marketCard('Benchmark value for quantity',marketFmt(total,2)+' PLN')+marketCard('Change vs matched reference',marketPct((pln/reference-1)*100))+marketCard('Quantity value difference',marketFmt((pln-reference)*tonnes,2)+' PLN');el('scenario-reference').textContent=`Matched reference ${scenarioReference.date}: ${marketFmt(scenarioReference.price,3)} EUR/t × ${marketFmt(scenarioReference.fx,6)} PLN per EUR = ${marketFmt(reference,3)} PLN/t.`}
function marketRefresh(){if(!Object.keys(data).length)return;marketSnapshot();marketAttribution();marketComparison();marketCorrelation();marketSpread();marketScenario()}
for(const id of ['attribution-period'])el(id).addEventListener('change',marketAttribution);
for(const id of ['comparison-range','comparison-units','comparison-instruments'])el(id).addEventListener('change',marketComparison);
for(const id of ['correlation-a','correlation-b','correlation-window'])el(id).addEventListener('change',marketCorrelation);
el('spread-units').addEventListener('change',marketSpread);el('distribution-years').addEventListener('change',marketDistribution);el('range').addEventListener('change',()=>{if(Object.keys(data).length){marketSnapshot();marketCorrelation();marketSpread()}});for(const id of ['scenario-price','scenario-fx','scenario-tonnes'])el(id).addEventListener('input',()=>marketScenario());el('scenario-reset').addEventListener('click',()=>marketScenario(true));
