/* A rendered, selected-section snapshot. No original series or application scripts. */
(function(root){
'use strict';
const HTML_TAGS=new Set('section div p h1 h2 h3 h4 span strong em small ul ol li table caption thead tbody tfoot tr th td figure figcaption br code pre'.split(' '));
const SVG_TAGS=new Set('svg g path line polyline polygon rect circle ellipse text tspan title desc'.split(' '));
const BLOCKED=new Set('script style link meta base iframe frame object embed img image use foreignobject animate animatetransform animatemotion set a input select option textarea button form label'.split(' '));
const CONTROL_CLASSES=new Set(['controls','checks','science-controls','market-controls','ux-preferences','report-controls']);
const CLASS_NAMES=new Set('cards card market-grid market-value market-legend matrix-reference matrix-key price-matrix-layout price-matrix price-lower price-higher price-equal missing muted positive negative notice science-note science-help ux-help ux-availability report-copy'.split(' '));
const SVG_NUMERIC=new Set('x y x1 x2 y1 y2 cx cy r rx ry width height dx dy stroke-width font-size opacity fill-opacity stroke-opacity stroke-dashoffset'.split(' '));
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
function paint(value){return /^(?:#[0-9a-f]{3,8}|(?:rgb|rgba)\([\d., %]+\)|none|transparent|currentColor|black|white|blue|red|green|orange|gray)$/i.test(value.trim())?value.trim():null;}
function safeStyles(value){const declarations=[];for(const part of String(value||'').split(';')){const colon=part.indexOf(':');if(colon<0)continue;const key=part.slice(0,colon).trim().toLowerCase(),val=part.slice(colon+1).trim();if(['color','background','background-color','fill','stroke','--line'].includes(key)){const safe=paint(val);if(safe)declarations.push(key+':'+safe);}else if(key==='font-weight'&&/^(?:normal|bold|[1-9]00)$/.test(val))declarations.push(key+':'+val);}return declarations.join(';');}
function sanitizedAttributes(node,svg){const attrs=[];for(const item of Array.from(node.attributes||[])){const name=item.name.toLowerCase(),value=String(item.value);let safe=null,key=name;
 if(name==='class'){safe=value.split(/\s+/).filter(c=>CLASS_NAMES.has(c)).join(' ');}
 else if(name==='style')safe=safeStyles(value);
 else if(['title','aria-label'].includes(name))safe=value;
 else if(name==='role'&&['img','status','rowheader','columnheader'].includes(value))safe=value;
 else if(!svg&&['colspan','rowspan'].includes(name)&&/^[1-9]\d{0,2}$/.test(value))safe=value;
 else if(!svg&&name==='scope'&&['col','row','colgroup','rowgroup'].includes(value))safe=value;
 else if(svg){
  if(name==='viewbox'&&/^[-+\d.eE ,]+$/.test(value)){safe=value;key='viewBox';}
  else if(SVG_NUMERIC.has(name)&&/^[-+\d.eE ,%]+$/.test(value))safe=value;
  else if(['stroke','fill'].includes(name))safe=paint(value);
  else if(['points','stroke-dasharray'].includes(name)&&/^[-+\d.eE ,]+$/.test(value))safe=value;
  else if(name==='d'&&/^[MmLlHhVvCcSsQqTtAaZz\d.eE+\-,\s]*$/.test(value))safe=value;
  else if(name==='text-anchor'&&['start','middle','end'].includes(value))safe=value;
  else if(name==='dominant-baseline'&&['auto','middle','central','hanging','alphabetic'].includes(value))safe=value;
  else if(['stroke-linecap','stroke-linejoin'].includes(name)&&/^(?:butt|round|square|miter|bevel)$/.test(value))safe=value;
  else if(name==='preserveaspectratio'&&/^(?:none|x(?:Min|Mid|Max)Y(?:Min|Mid|Max)(?: (?:meet|slice))?)$/.test(value)){safe=value;key='preserveAspectRatio';}
  else if(name==='transform'&&/^(?:(?:matrix|translate|scale|rotate|skewX|skewY)\([-+\d.eE ,]+\)\s*)+$/.test(value))safe=value;
 }
 if(safe)attrs.push(key+'="'+esc(safe)+'"');
}if(svg&&String(node.tagName).toLowerCase()==='svg')attrs.push('xmlns="http://www.w3.org/2000/svg"');return attrs.length?' '+attrs.join(' '):'';}
function serialize(node,inSVG=false){
 if(!node)return '';if(node.nodeType===3)return esc(node.nodeValue);if(node.nodeType!==1)return '';
 const tag=String(node.tagName).toLowerCase(),inlineHidden=node.style?.display==='none'||Array.from(node.attributes||[]).some(a=>a.name.toLowerCase()==='style'&&/(?:^|;)\s*display\s*:\s*none(?:\s*!important)?\s*(?:;|$)/i.test(a.value));if(BLOCKED.has(tag)||node.hidden||node.hasAttribute?.('hidden')||inlineHidden)return '';
 if(node.id==='science-fundamental-import'||node.id==='science-fundamental-error'||node.id==='science-fundamental-review')return '';
 if(Array.from(node.classList||[]).some(c=>CONTROL_CLASSES.has(c)))return '';
 const svg=inSVG||tag==='svg';if(svg&&!SVG_TAGS.has(tag))return '';
 const children=()=>Array.from(node.childNodes||[]).map(child=>serialize(child,svg)).join('');
 if(tag==='details')return '<div class="report-copy">'+children()+'</div>';
 if(tag==='summary')return '<h3>'+children()+'</h3>';
 if(!svg&&!HTML_TAGS.has(tag))return children();
 const attrs=sanitizedAttributes(node,svg);return '<'+tag+attrs+'>'+children()+(tag==='br'?'':'</'+tag+'>');
}
const REPORT_CSS=`
*{box-sizing:border-box}body{margin:0;background:#fff;color:#172b43;font:14px/1.5 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:24px}h1{font-size:27px;margin:0 0 12px}h2{font-size:20px;margin:0 0 12px}h3{font-size:15px;margin:12px 0 6px}.report-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px 16px}.report-meta dt{font-weight:600}.report-meta dd{margin:0;overflow-wrap:anywhere}.report-section{padding:18px 0;border-top:1px solid #cad5e4;margin:18px 0}.report-settings{font-size:12px;color:#53657e;margin-bottom:12px}.report-notice{border-left:4px solid #b8790b;background:#fff7e5;padding:10px 14px}.cards,.market-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.card{border:1px solid #dce4ef;border-radius:7px;background:#f8fafc;padding:12px;overflow-wrap:anywhere}.card strong{display:block;font-size:20px}.muted,.science-note{color:#53657e;font-size:12px}.positive{color:#166534}.negative{color:#9f1239}table{width:100%;border-collapse:collapse;font-size:11px;table-layout:auto}caption{text-align:left;font-weight:600;padding:8px 0}th,td{padding:5px;border-bottom:1px solid #dce4ef;text-align:right;white-space:normal;overflow-wrap:anywhere}th:first-child{text-align:left}thead{background:#f1f5f9}tr{break-inside:avoid}figure{margin:12px 0}figcaption{font-size:12px}svg{display:block;width:100%;height:auto;max-width:100%;min-width:0}svg text{font:12px system-ui,sans-serif;fill:#4b5d76}svg,.card{break-inside:avoid}.market-legend{display:flex;gap:12px;flex-wrap:wrap;font-size:12px;margin:8px 0}.market-legend span:before{content:"";display:inline-block;width:20px;height:3px;background:var(--line);vertical-align:middle;margin-right:6px}.price-matrix-layout{display:block}.matrix-reference{font-size:12px;margin:8px 0}.matrix-key{display:flex;flex-wrap:wrap;gap:9px}.price-lower{background:#d8edca;color:#254718}.price-higher{background:#f9d4d9;color:#842337}.price-equal{background:#dbeafe;color:#183e80}.missing{background:#f1f5f9;color:#65758e}.report-copy{margin:10px 0}.report-copy h3{font-size:14px}.report-footer{font-size:12px;color:#53657e;border-top:1px solid #cad5e4;padding-top:12px}code,pre{overflow-wrap:anywhere;white-space:pre-wrap}h2,h3{break-after:avoid}@page{size:A4 landscape;margin:12mm}@media(max-width:700px){main{padding:12px}.report-meta{grid-template-columns:1fr}.cards,.market-grid{grid-template-columns:repeat(2,minmax(0,1fr))}table{font-size:10px}th,td{padding:3px}}@media print{body{font-size:10pt}main{max-width:none;padding:0}.report-section{padding:12px 0}.report-meta{font-size:9pt}table{font-size:8pt}thead{display:table-header-group}.report-settings,.report-footer{font-size:8pt}svg{max-height:165mm}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}}`;
function metadata(context){if(!context||typeof context!=='object')throw Error('Select an instrument before building a report.');const fields=['title','unit','asOf','source','provenance'];const out={};for(const field of fields){if(typeof context[field]!=='string'||!context[field].trim())throw Error('Report context is missing '+field+'.');out[field]=context[field];}if(!/^\d{4}-\d{2}-\d{2}$/.test(out.asOf))throw Error('Report cutoff must be an explicit ISO date.');const [year,month,day]=out.asOf.split('-').map(Number),date=new Date(0);date.setUTCFullYear(year,month-1,day);if(year<1||date.getUTCFullYear()!==year||date.getUTCMonth()!==month-1||date.getUTCDate()!==day)throw Error('Report cutoff is not a valid calendar date.');out.semantics=String(context.semantics||'Not specified');return out;}
function settingsFor(document,ids){return (ids||[]).map(id=>{const control=document.getElementById(id);if(!control)return null;const label=control.closest?.('label'),labelText=label?Array.from(label.childNodes||[]).filter(node=>node!==control).map(node=>node.textContent||node.nodeValue||'').join(' ').trim():id;let value;if(control.type==='checkbox')value=control.checked?'Enabled':'Hidden';else if(String(control.tagName).toLowerCase()==='select')value=control.selectedOptions?.[0]?.textContent||control.value;else value=control.value;return (labelText||id)+': '+String(value??'');}).filter(Boolean);}
function buildSnapshot(document,context,sections,createdAt){const meta=metadata(context);if(!Array.isArray(sections)||!sections.length)throw Error('Select at least one report section.');let body='<header><h1>'+esc(meta.title)+' — analysis report</h1><dl class="report-meta">';for(const [key,value]of [['Display units',meta.unit],['Analysis cutoff',meta.asOf],['Source',meta.source],['Provenance',meta.provenance],['Quote definition',meta.semantics],['Snapshot created',createdAt]])body+='<div><dt>'+esc(key)+'</dt><dd>'+esc(value)+'</dd></div>';body+='</dl><p class="report-notice">Snapshot of the selected analyses and settings. Historical results describe the supplied benchmark observations; they do not guarantee future outcomes. A dash denotes an unavailable value, not zero. Dates, units, sample counts and current settings are recorded below.</p></header>';
 for(const section of sections){body+='<section class="report-section"><h2>'+esc(section.label)+'</h2>';const settings=settingsFor(document,section.settings);if(settings.length)body+='<p class="report-settings">'+settings.map(esc).join(' · ')+'</p>';let found=false;for(const id of section.targets||[]){const node=document.getElementById(id);if(node){const content=serialize(node);if(content.trim()){found=true;body+=content;}}}if(!found)body+='<p>Unavailable: no rendered result for this section.</p>';body+='</section>';}
 body+='<footer class="report-footer">SeasonLens · This fixed snapshot contains only the chosen rendered sections and their method explanations. It contains no original observation dataset or application code. Exported reports can still contain private results and declared source information. Private results remain in this file. Share only if permitted. Separate fundamental context is not automatically matched to the selected price instrument. Rebuild the report after changing the analysis.</footer>';
 const title=meta.title+' — SeasonLens report';const documentHTML='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src \'none\'; object-src \'none\'; base-uri \'none\'; form-action \'none\'"><title>'+esc(title)+'</title><style>'+REPORT_CSS+'</style></head><body><main>'+body+'</main></body></html>';
 return Object.freeze({body,html:documentHTML,title,asOf:meta.asOf,sectionCount:sections.length,createdAt});}
function initSeasonLensReport(options){const document=root.document,host=document.getElementById('report-export-panel');if(!host)return {close:function(){}};if(host._seasonLensReport)return host._seasonLensReport;
 const el=id=>document.getElementById(id),make=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};const configured=(options.sections||[]).filter(section=>section&&typeof section.id==='string');let snapshot=null,returnFocus=null,token=0;
 for(const section of configured){const label=make('label'),input=make('input');input.type='checkbox';input.value=section.id;input.checked=Boolean(section.default);input.id='report-include-'+section.id;label.append(input,make('span',section.label));el('report-sections').append(label);}
 const selected=()=>configured.filter(section=>el('report-include-'+section.id)?.checked);const settingSignature=sections=>JSON.stringify(sections.map(s=>(s.settings||[]).map(id=>{const control=el(id);return [id,control?.type==='checkbox'?Boolean(control.checked):String(control?.value??'')];})));const status=message=>{el('report-status').textContent=message;};
 function close(){el('seasonlens-report-preview').hidden=true;document.body.classList.remove('seasonlens-report-open');returnFocus?.focus?.();}
 function disable(value){el('report-build').disabled=value;}
 async function build(){const mine=++token;disable(true);status('Building selected sections…');const focus=document.activeElement;try{const sections=selected();if(!sections.length)throw Error('Select at least one report section.');const before=metadata(options.context()),settings=settingSignature(sections);await options.prepareScience?.(sections.map(section=>section.id));if(mine!==token)return;
 const current=metadata(options.context());if(JSON.stringify(current)!==JSON.stringify(before)||settingSignature(sections)!==settings||JSON.stringify(selected().map(s=>s.id))!==JSON.stringify(sections.map(s=>s.id)))throw Error('Analysis or report selection changed during preparation. Build the report again.');
 const next=buildSnapshot(document,current,sections,new Date().toISOString());snapshot=next;returnFocus=focus;el('report-preview-status').textContent='';el('seasonlens-report-content').innerHTML=next.body;el('seasonlens-report-preview').hidden=false;document.body.classList.add('seasonlens-report-open');el('report-snapshot-label').textContent=next.title+' · cutoff '+next.asOf+' · '+next.sectionCount+' sections · fixed snapshot';status('Report ready. Print / Save PDF opens your browser’s print dialog. Download HTML saves this snapshot.');el('report-close').focus();
 }catch(error){status('Report not built: '+error.message);}finally{if(mine===token)disable(false);}}
 el('report-build').addEventListener('click',build);el('report-close').addEventListener('click',close);
 el('report-print').addEventListener('click',()=>{if(!snapshot){status('Build a report before printing.');return;}if(typeof root.print!=='function'){el('report-preview-status').textContent='Printing is unavailable here. Download HTML, open it in a browser, then use Print / Save PDF.';return;}try{root.print();}catch(error){el('report-preview-status').textContent='The print dialog could not open. Download HTML and print it in a browser.';}});
 el('report-download').addEventListener('click',()=>{if(!snapshot)return;let url=null;try{const blob=new root.Blob([snapshot.html],{type:'text/html;charset=utf-8'});url=root.URL.createObjectURL(blob);const a=make('a');a.href=url;a.download='seasonlens-report-'+snapshot.asOf+'.html';document.body.append(a);a.click();a.remove();root.setTimeout(()=>root.URL.revokeObjectURL(url),1000);el('report-preview-status').textContent='HTML snapshot downloaded. It may contain private analytical results; share only with appropriate permission.';}catch(error){if(url)root.URL.revokeObjectURL(url);el('report-preview-status').textContent='Download could not start: '+error.message;}});
 document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!el('seasonlens-report-preview').hidden){event.preventDefault();close();}});
 const api={build,close};host._seasonLensReport=api;return api;}
const api=Object.freeze({serialize,buildSnapshot,metadata,settingsFor,reportCSS:REPORT_CSS,initSeasonLensReport});root.SeasonLensReport=api;root.initSeasonLensReport=initSeasonLensReport;if(typeof module==='object'&&module.exports)module.exports=api;
})(globalThis);
