/* Private, descriptive scientific panels. No provider requests or persistent data. */
(function(root){
'use strict';
function initSeasonLensScience(options){
 const document=root.document,host=document.getElementById('scientific-analysis');
 if(!host)return {refresh:function(){}};
 if(host._seasonLensScience)return host._seasonLensScience;
 const {data,view,cutoff,chart,esc,fmt,card,marketFXId}=options;
 const C=root.SeasonLensScienceCommon,R=root.SeasonLensRisk,S=root.SeasonLensSeasonalStats,F=root.SeasonLensForecasts,B=root.SeasonLensFundamentals;
 const el=id=>document.getElementById(id),text=(id,value)=>{el(id).textContent=value;},html=(id,value)=>{el(id).innerHTML=value;};
 const pct=value=>value===null||value===undefined?'—':fmt(value,2)+'%';
 const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
 const cache=[];let privateFundamental=[],staged=null,fileToken=0,previousCutoff=null;
 const demoFundamental=B.demoRows();
 function cached(kind,a,b,key,calculate){const found=cache.find(item=>item.kind===kind&&item.a===a&&item.b===b&&item.key===key);if(found)return found.result;const result=calculate();cache.push({kind,a,b,key,result});if(cache.length>24)cache.shift();return result;}
 function startDate(){const period=el('science-period').value;if(period==='all')return null;const asOf=cutoff(),months=period==='1y'?-12:-60;try{return C.monthShift(asOf,months)}catch(error){if(Number(asOf.slice(0,4))<=(period==='1y'?1:5))return '0001-01-01';throw error;}}
 function selected(){const id=el('instrument').value,s=data[id],v=view();if(!s||!v)throw Error('Select an available price instrument.');return {id,s,v};}
 function visibleWindow(rows){const visible=C.validateRows(rows,cutoff()),start=startDate();return start?visible.filter(r=>r.date>=start):visible;}
 function provenance(s){return s.source==='SYNTHETIC'?'SYNTHETIC — invented demonstration':s.source==='USER_FILE'?'USER_FILE — private in this tab':String(s.source||'Unspecified source');}
 function table(headers,rows,caption=''){return '<table>'+(caption?'<caption>'+esc(caption)+'</caption>':'')+'<thead><tr>'+headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map((v,i)=>'<'+(i?'td':'th scope="row"')+'>'+esc(String(v??'—'))+'</'+(i?'td':'th')+'>').join('')+'</tr>').join('')+'</tbody></table>';}
 function guard(name,render,targets){try{render()}catch(error){for(const id of targets)html(id,'');text('science-'+name+'-status','This panel is unavailable: '+error.message);}}
 function histogram(bins){if(!bins.length){html('science-risk-histogram','<p>No valid percentage changes.</p>');return;}
  const maximum=Math.max(...bins.map(b=>b.count)),width=650,left=60,bottom=205,step=550/bins.length;
  let svg='<figure><svg viewBox="0 0 650 270" role="img" aria-label="Historical percentage-change histogram"><title>Historical percentage-change histogram</title><text x="60" y="20">Observation count</text>';
  [0,.5,1].forEach(p=>{const y=bottom-160*p;svg+='<line x1="60" x2="610" y1="'+y+'" y2="'+y+'" stroke="#cbd5e1"/><text x="50" y="'+(y+4)+'" text-anchor="end">'+fmt(maximum*p,0)+'</text>';});
  bins.forEach((bin,i)=>{const height=maximum?bin.count/maximum*160:0;svg+='<rect x="'+(left+i*step+2)+'" y="'+(bottom-height)+'" width="'+Math.max(1,step-4)+'" height="'+height+'" fill="#2563eb"><title>'+esc(fmt(bin.lower,3)+'% to '+fmt(bin.upper,3)+'%: '+bin.count+' changes')+'</title></rect>';});
  svg+='<text x="60" y="230">'+esc(pct(bins[0].lower))+'</text><text x="610" y="230" text-anchor="end">'+esc(pct(bins.at(-1).upper))+'</text><text x="330" y="255" text-anchor="middle">Price change (%)</text></svg><figcaption>Blue bars: count of historical percentage changes, regardless of buyer/seller perspective. Hover a bar for its boundaries and count.</figcaption></figure>';html('science-risk-histogram',svg);
 }
 function renderExposure(r,rows,unit){const amount=Number(el('science-quantity').value),last=rows.at(-1),commodity=/\/t$/.test(unit),fx=/^[A-Z]{3} per [A-Z]{3}$/.test(unit),currency=commodity?unit.slice(0,-2):fx?unit.slice(0,3):null;
  text('science-quantity-label',commodity?'Quantity in tonnes':fx?'Amount in '+unit.slice(-3):'Quantity in supplied quote units');
  if(!currency){html('science-exposure','<p>Budget exposure requires an explicitly recognized commodity or currency quote unit.</p>');return;}
  if(el('science-quantity').value.trim()===''||!Number.isFinite(amount)||amount<=0){html('science-exposure','<p>Enter a finite positive quantity to calculate budget exposure.</p>');return;}
  if(!last||last.value<=0||!r.available){html('science-exposure','<p>Budget exposure requires a positive last visible quote and available historical tail estimates.</p>');return;}
  const budget=last.value*amount,varCost=budget*(r.var/100),esCost=budget*(r.expectedShortfall/100);
  if(![budget,varCost,esCost].every(Number.isFinite)){html('science-exposure','<p>Budget exposure exceeds the numerical range.</p>');return;}
  html('science-exposure',card('Current benchmark budget',fmt(budget,2)+' '+currency,'Quote date '+last.date)+card('Signed VaR budget change',fmt(varCost,2)+' '+currency)+card('Signed ES budget change',fmt(esCost,2)+' '+currency,'Arithmetic adverse change; not a futures holding P&L.'));
 }
 function risk(){const {v}=selected(),horizon=Number(el('science-horizon').value),confidence=Number(el('science-confidence').value),direction=el('science-direction').value,key=[cutoff(),startDate(),horizon,confidence,direction].join('|'),rows=visibleWindow(v.daily);
  const result=cached('risk',v.daily,null,key,()=>({risk:R.historicalRisk(rows,{asOf:cutoff(),horizon,confidence,direction}),stress:R.stressEpisodes(rows,{asOf:cutoff(),horizon})})),r=result.risk,stress=result.stress;
  text('science-risk-status',r.counts.validIntervals+' valid changes from '+r.counts.observations+' observations'+(rows.length?' · '+rows[0].date+'–'+rows.at(-1).date:'')+' · '+r.counts.nonpositiveEndpoints+' nonpositive-endpoint intervals excluded · tail mass '+fmt(r.tailMass,2)+'. '+(r.available?'Historical estimates only.':r.unavailableReason)+(r.overlapping?' Multi-interval changes overlap and are dependent.':''));
  html('science-risk-cards',card('Historical '+fmt(confidence*100,0)+'% VaR',pct(r.var),direction+' adverse-change perspective')+card('Historical Expected Shortfall',pct(r.expectedShortfall),'Fractionally weighted worst tail')+card('Mean price change',pct(r.meanChange))+card('Median price change',pct(r.medianChange)));
  renderExposure(r,rows,v.unit);histogram(r.histogram);
  const note=row=>row?row.start+'–'+row.end+' · '+row.observedIntervals+' observed intervals':'No positive-price path available';
  html('science-stress-cards',card('Maximum peak-to-trough change',pct(stress.maxDecline?.change),note(stress.maxDecline))+card('Maximum trough-to-peak change',pct(stress.maxRise?.change),note(stress.maxRise)));
  const extremes=[...stress.largestRises.map(r=>['Rise',r]),...stress.largestFalls.map(r=>['Fall',r])];
  html('science-stress-table',table(['Episode','Start','End','Observed intervals','Change'],extremes.map(([name,r])=>[name,r.start,r.end,r.observedIntervals,pct(r.change)]),'Largest observed benchmark moves · '+stress.nonpositivePathBreaks+' nonpositive quotes break ratio paths'));
 }
 function seasonal(){const {v}=selected(),windowYears=el('science-seasonal-years').value==='all'?'all':Number(el('science-seasonal-years').value),key=cutoff()+'|'+windowYears;
  const r=cached('seasonal',v.daily,null,key,()=>S.analyze(v.daily,{asOf:cutoff(),windowYears,bootstrapReplicates:1000,seed:20261008}));
  text('science-seasonal-status',r.startYear+'–'+r.endYear+' declared completed years. Current year excluded ('+r.omissions.currentYearRows+' observations). Fixed early/late split: '+r.earlyYears.startYear+'–'+r.earlyYears.endYear+' / '+r.lateYears.startYear+'–'+r.lateYears.endYear+'. Missing current months: '+r.omissions.missingMonthClose+'; missing previous months: '+r.omissions.missingPreviousMonth+'; nonpositive month endpoints: '+r.omissions.nonpositiveMonthEndpoints+'. Dashed limits are approximate intervals of the historical mean, not future-price ranges.');
  const rows=r.months.map(m=>({...m,date:'2000-'+String(m.month).padStart(2,'0')+'-01',label:months[m.month-1]}));
  chart('science-seasonal-chart',rows,[{key:'mean',name:'Equal-year mean monthly change',color:'#2563eb'},{key:'median',name:'Median monthly change',color:'#c45d11'},{key:'bootstrapLow',name:'Approximate historical-mean 95% lower limit',color:'#7c3aed',dash:true},{key:'bootstrapHigh',name:'Approximate historical-mean 95% upper limit',color:'#7c3aed',dash:true}],{unit:'Monthly benchmark price change (%)'});
  html('science-seasonal-table',table(['Month','Mean','Median','Positive years (%)','Years','Early mean (n)','Late mean (n)','Leave-one-year-out range','Approx. 95% mean interval'],r.months.map(m=>[months[m.month-1],pct(m.mean),pct(m.median),m.positiveFraction===null?'—':pct(m.positiveFraction*100),m.yearCount+'/'+r.yearCount,pct(m.earlyMean)+' ('+m.earlyCount+')',pct(m.lateMean)+' ('+m.lateCount+')',m.leaveOneOutMinimum===null?'—':pct(m.leaveOneOutMinimum)+' to '+pct(m.leaveOneOutMaximum),m.bootstrapLow===null?'Unavailable: '+m.bootstrapReason:pct(m.bootstrapLow)+' to '+pct(m.bootstrapHigh)+' ('+m.bootstrapValidReplicates+'/1000 replicates)'])));
  html('science-seasonal-years-table',table(['Year',...months],r.yearly.map(y=>[y.year,...y.returns.map(pct)]),'Each completed year contributes at most one change per month; — means unavailable.'));
 }
 function compatibleFX(s,fxId){if(!fxId||!data[fxId]||s.views?.Original?.unit!=='EUR/t'||data[fxId].views?.Original?.unit!=='PLN per EUR')return false;const fx=data[fxId];if(s.source==='USER_FILE')return fx.source==='USER_FILE'&&Boolean(s.import_group)&&fx.import_group===s.import_group&&fx.role==='eur_pln';if(s.source==='SYNTHETIC')return fx.source==='SYNTHETIC';return fx.source!=='USER_FILE'&&fx.source!=='SYNTHETIC';}
 function fx(){const {s}=selected(),fxId=marketFXId(s);if(!compatibleFX(s,fxId)){text('science-fx-status','Unavailable: select an original EUR/t commodity with explicitly compatible EUR/PLN. Private workbooks require a declared same-import-group EUR/PLN role. Invented FX is never substituted.');html('science-fx-cards','');html('science-fx-table','');return;}
  const commodity=s.views.Original.daily,fxSeries=data[fxId].views.Original.daily,key=cutoff()+'|'+startDate(),r=cached('fx',commodity,fxSeries,key,()=>R.fxRisk(visibleWindow(commodity),visibleWindow(fxSeries),{asOf:cutoff()}));
  text('science-fx-status',provenance(s)+' + '+provenance(data[fxId])+'. '+r.counts.pairedIntervals+' exact matching intervals'+(r.intervals.length?' · '+r.intervals[0].start+'–'+r.intervals.at(-1).end:'')+'; original positive-endpoint intervals: commodity '+r.counts.commodityIntervals+', FX '+r.counts.fxIntervals+'. Nonpositive-endpoint exclusions: '+r.counts.commodityNonpositiveEndpoints+' / '+r.counts.fxNonpositiveEndpoints+'. '+(r.unavailableReason||'Sample variance of matched percentage-log changes; not causal attribution.'));
  html('science-fx-cards',card('Commodity Euler variance share',pct(r.commodityShare),'Negative and >100% shares are retained')+card('FX Euler variance share',pct(r.fxShare))+card('Combined sample variance',fmt(r.totalVar,6),'Squared percentage-log-change units'));
  html('science-fx-table',table(['Component','Sample variance / covariance','Euler contribution','Share'],[['Commodity',fmt(r.varCommodity,6),fmt(r.commodityContribution,6),pct(r.commodityShare)],['FX',fmt(r.varFX,6),fmt(r.fxContribution,6),pct(r.fxShare)],['Cross covariance',fmt(r.covariance,6),'Included once in each contribution','—']], 'Total = commodity variance + FX variance + 2 × covariance'));
 }
 function forecast(){const {v}=selected(),key=cutoff()+'|'+startDate(),r=cached('forecast',v.daily,null,key,()=>F.evaluate(v.daily,{asOf:cutoff(),startDate:startDate(),horizons:[1,5,20],minTraining:200,maxOrigins:252}));
  text('science-forecast-status','Evaluation origins and later targets: '+(r.startDate||'first available origin')+'–'+r.asOf+'. '+r.visibleCount+' observations available for training; at least '+r.minTraining+' at every origin. At most '+r.maxOrigins+' most recent eligible origins per horizon, shared by all three fixed models.');
  const rows=[];for(const h of r.horizons){for(const model of h.models)rows.push([h.horizon,model.label,h.count,fmt(model.mae,4),fmt(model.rmse,4),pct(model.maeSkill===null?null:model.maeSkill*100),pct(model.rmseSkill===null?null:model.rmseSkill*100),h.reason||h.firstOriginDate+'–'+h.lastOriginDate,h.reason?'—':h.firstTargetDate+'–'+h.lastTargetDate,h.eligibleOriginCount+' / '+h.limitedOriginCount]);}
  html('science-forecast-table',table(['Observed-step horizon','Fixed model','Origins','MAE','RMSE','MAE skill vs last price','RMSE skill vs last price','Origin dates / unavailable reason','Target dates','Eligible / omitted by cap'],rows,'Errors in '+v.unit+' · no future model tuning, profitability or guaranteed predictive skill'));
 }
 function fillSelect(id,values){const select=el(id),old=select.value;select.replaceChildren();for(const value of values){const option=document.createElement('option');option.value=value;option.textContent=value;select.append(option);}if(values.includes(old))select.value=old;select.disabled=!values.length;}
 function fundamentalRows(){return el('science-fundamental-source').value==='private'?privateFundamental:demoFundamental;}
 function fundamental(){const privateSource=el('science-fundamental-source').value==='private',rows=fundamentalRows(),visible=rows.filter(r=>r.publication_date<=cutoff());el('science-fundamental-import').hidden=!privateSource;
  fillSelect('science-fundamental-commodity',[...new Set(visible.map(r=>r.commodity))].sort());const commodity=el('science-fundamental-commodity').value;
  fillSelect('science-fundamental-region',[...new Set(visible.filter(r=>r.commodity===commodity).map(r=>r.region))].sort());const region=el('science-fundamental-region').value;
  fillSelect('science-fundamental-year',[...new Set(visible.filter(r=>r.commodity===commodity&&r.region===region).map(r=>r.marketing_year))].sort().reverse());const marketingYear=el('science-fundamental-year').value;
  if(!commodity||!region||!marketingYear){text('science-fundamental-status',privateSource&&!rows.length?'Validate and add your private normalized CSV. No price-instrument join is performed.':'No fundamental release on or before '+cutoff()+'. Future publications are not selectable.');html('science-fundamental-cards','');html('science-fundamental-table','');return;}
  const source=privateSource?'USER_FILE':'SYNTHETIC',key=[cutoff(),commodity,region,marketingYear,source].join('|'),r=cached('fundamental',rows,null,key,()=>B.analyze(rows,{asOf:cutoff(),commodity,region,marketingYear,source}));
  text('science-fundamental-status',source+(privateSource?' — private normalized import':' — invented example, not official data')+' · '+commodity+' / '+region+' / '+marketingYear+' · cutoff '+cutoff()+' · '+r.counts.selected+' dated releases selected; '+r.counts.after_cutoff+' future publications excluded from the entire dataset.');
  if(!r.available){html('science-fundamental-cards','<p>'+esc(r.reason)+'</p>');html('science-fundamental-table','');return;}
  html('science-fundamental-cards',card('Latest stocks-to-use',pct(r.latest.stocks_to_use_percent),'Published '+r.latest.publication_date)+card('Revision vs previous release',r.latest.stocks_to_use_change_pp===null?'—':fmt(r.latest.stocks_to_use_change_pp,2)+' percentage points','Same commodity, region and marketing year')+card('Ending stocks / total use',fmt(r.latest.ending_stocks,3)+' / '+fmt(r.latest.total_use,3),r.latest.unit));
  html('science-fundamental-table',table(['Publication','Marketing year','Stocks','Total use','Stocks-to-use','Ratio revision (pp)','Unit'],r.revisions.map(row=>[row.publication_date,row.marketing_year,fmt(row.ending_stocks,3),fmt(row.total_use,3),pct(row.stocks_to_use_percent),fmt(row.stocks_to_use_change_pp,3),row.unit]),source+' · releases through the explicit cutoff only'));
 }
 const panels=[['risk',risk,['science-risk-cards','science-exposure','science-risk-histogram','science-stress-cards','science-stress-table']],['seasonal',seasonal,['science-seasonal-chart','science-seasonal-table','science-seasonal-years-table']],['fx',fx,['science-fx-cards','science-fx-table']],['forecast',forecast,['science-forecast-table']],['fundamental',fundamental,['science-fundamental-cards','science-fundamental-table']]];
 function invalidate(message){fileToken++;staged=null;el('science-fundamental-add').hidden=true;text('science-fundamental-review',message||'');}
 function refresh(){if(previousCutoff!==null&&previousCutoff!==cutoff())invalidate('Cutoff changed. Review your fundamental CSV again before adding.');previousCutoff=cutoff();try{const {s,v}=selected();text('science-context',s.title+' · '+v.unit+' · '+provenance(s)+' · analysis cutoff '+cutoff()+' · risk/FX/forecast window '+(startDate()||'all supplied history')+'–'+cutoff()+'.')}catch(error){text('science-context',error.message);}for(const [name,render,targets]of panels)if(el('science-'+name+'-panel').open)guard(name,render,targets);}
 const controls=['science-period','science-direction','science-horizon','science-confidence','science-quantity','science-seasonal-years','science-fundamental-commodity','science-fundamental-region','science-fundamental-year'];
 for(const id of controls)el(id).addEventListener(id==='science-quantity'?'input':'change',refresh);
 for(const [name,render,targets]of panels)el('science-'+name+'-panel').addEventListener('toggle',()=>{if(el('science-'+name+'-panel').open)guard(name,render,targets);});
 el('science-fundamental-source').addEventListener('change',()=>{invalidate();refresh();});
 el('science-fundamental-file').addEventListener('change',()=>{invalidate('File changed. Validate and review again.');text('science-fundamental-error','');});
 el('science-fundamental-read').addEventListener('click',async()=>{invalidate();const token=fileToken,file=el('science-fundamental-file').files?.[0];text('science-fundamental-error','');try{if(!file)throw Error('Choose a normalized CSV file.');if(!/\.csv$/i.test(file.name))throw Error('Choose a .csv file.');if(!Number.isFinite(file.size)||file.size>B.MAX_BYTES)throw Error('Fundamental CSV exceeds the supported file size.');const buffer=await file.arrayBuffer();if(token!==fileToken)return;const content=new TextDecoder('utf-8',{fatal:true}).decode(buffer),rows=B.parseCSV(content),visible=rows.filter(r=>r.publication_date<=cutoff());staged={rows,asOf:cutoff(),token};text('science-fundamental-review','Validated '+rows.length+' releases; '+visible.length+' on or before '+cutoff()+'; '+(rows.length-visible.length)+' future releases excluded. '+new Set(visible.map(r=>r.commodity+' / '+r.region)).size+' explicit commodity / region groups. Source: USER_FILE, private in this tab. Adding replaces only your existing private fundamental dataset.');el('science-fundamental-add').hidden=false;}catch(error){if(token!==fileToken)return;staged=null;text('science-fundamental-error','CSV rejected: '+error.message);el('science-fundamental-add').hidden=true;}});
 el('science-fundamental-add').addEventListener('click',()=>{if(!staged||staged.token!==fileToken||staged.asOf!==cutoff())return;privateFundamental=staged.rows;staged=null;el('science-fundamental-add').hidden=true;text('science-fundamental-review','Private fundamental dataset added to this tab. Reload removes it.');refresh();});
 const api={refresh};host._seasonLensScience=api;refresh();return api;
}
root.initSeasonLensScience=initSeasonLensScience;
if(typeof module!=='undefined'&&module.exports)module.exports=initSeasonLensScience;
})(globalThis);
